name = "Chin"
uuid = "ceb11618-883e-4e51-9f71-e47fdaf17ef3"
authors = ["1s22s1 <1s22s1@example.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
